/*
------------------------------------------------------------------------------ 
This code was generated by Amplication. 
 
Changes to this file will be lost if the code is regenerated. 

There are other ways to to customize your code, see this doc to learn more
https://docs.amplication.com/how-to/custom-code

------------------------------------------------------------------------------
  */
import * as graphql from "@nestjs/graphql";
import { GraphQLError } from "graphql";
import { isRecordNotFoundError } from "../../prisma.util";
import { MetaQueryPayload } from "../../util/MetaQueryPayload";
import * as nestAccessControl from "nest-access-control";
import * as gqlACGuard from "../../auth/gqlAC.guard";
import { GqlDefaultAuthGuard } from "../../auth/gqlDefaultAuth.guard";
import * as common from "@nestjs/common";
import { AclFilterResponseInterceptor } from "../../interceptors/aclFilterResponse.interceptor";
import { AclValidateRequestInterceptor } from "../../interceptors/aclValidateRequest.interceptor";
import { Adresse } from "./Adresse";
import { AdresseCountArgs } from "./AdresseCountArgs";
import { AdresseFindManyArgs } from "./AdresseFindManyArgs";
import { AdresseFindUniqueArgs } from "./AdresseFindUniqueArgs";
import { CreateAdresseArgs } from "./CreateAdresseArgs";
import { UpdateAdresseArgs } from "./UpdateAdresseArgs";
import { DeleteAdresseArgs } from "./DeleteAdresseArgs";
import { AdresseService } from "../adresse.service";
@common.UseGuards(GqlDefaultAuthGuard, gqlACGuard.GqlACGuard)
@graphql.Resolver(() => Adresse)
export class AdresseResolverBase {
  constructor(
    protected readonly service: AdresseService,
    protected readonly rolesBuilder: nestAccessControl.RolesBuilder
  ) {}

  @graphql.Query(() => MetaQueryPayload)
  @nestAccessControl.UseRoles({
    resource: "Adresse",
    action: "read",
    possession: "any",
  })
  async _adressesMeta(
    @graphql.Args() args: AdresseCountArgs
  ): Promise<MetaQueryPayload> {
    const result = await this.service.count(args);
    return {
      count: result,
    };
  }

  @common.UseInterceptors(AclFilterResponseInterceptor)
  @graphql.Query(() => [Adresse])
  @nestAccessControl.UseRoles({
    resource: "Adresse",
    action: "read",
    possession: "any",
  })
  async adresses(
    @graphql.Args() args: AdresseFindManyArgs
  ): Promise<Adresse[]> {
    return this.service.adresses(args);
  }

  @common.UseInterceptors(AclFilterResponseInterceptor)
  @graphql.Query(() => Adresse, { nullable: true })
  @nestAccessControl.UseRoles({
    resource: "Adresse",
    action: "read",
    possession: "own",
  })
  async adresse(
    @graphql.Args() args: AdresseFindUniqueArgs
  ): Promise<Adresse | null> {
    const result = await this.service.adresse(args);
    if (result === null) {
      return null;
    }
    return result;
  }

  @common.UseInterceptors(AclValidateRequestInterceptor)
  @graphql.Mutation(() => Adresse)
  @nestAccessControl.UseRoles({
    resource: "Adresse",
    action: "create",
    possession: "any",
  })
  async createAdresse(
    @graphql.Args() args: CreateAdresseArgs
  ): Promise<Adresse> {
    return await this.service.createAdresse({
      ...args,
      data: args.data,
    });
  }

  @common.UseInterceptors(AclValidateRequestInterceptor)
  @graphql.Mutation(() => Adresse)
  @nestAccessControl.UseRoles({
    resource: "Adresse",
    action: "update",
    possession: "any",
  })
  async updateAdresse(
    @graphql.Args() args: UpdateAdresseArgs
  ): Promise<Adresse | null> {
    try {
      return await this.service.updateAdresse({
        ...args,
        data: args.data,
      });
    } catch (error) {
      if (isRecordNotFoundError(error)) {
        throw new GraphQLError(
          `No resource was found for ${JSON.stringify(args.where)}`
        );
      }
      throw error;
    }
  }

  @graphql.Mutation(() => Adresse)
  @nestAccessControl.UseRoles({
    resource: "Adresse",
    action: "delete",
    possession: "any",
  })
  async deleteAdresse(
    @graphql.Args() args: DeleteAdresseArgs
  ): Promise<Adresse | null> {
    try {
      return await this.service.deleteAdresse(args);
    } catch (error) {
      if (isRecordNotFoundError(error)) {
        throw new GraphQLError(
          `No resource was found for ${JSON.stringify(args.where)}`
        );
      }
      throw error;
    }
  }
}
